[workspace]
resolver = "2"
members = [
    "capi",
    "winit",
    "backend-winit-common",
    "examples/hello",
    "examples/confirm_before_quit",
    "examples/ios_hello",
    "examples/binding_test",
    "examples/ddcore",
    "examples/presentation",
    "examples/cef_e2e",
    "examples/native_e2e",
    "examples/native_e2e_driver",
    "examples/storage_e2e",
    "examples/single_instance_e2e",
]
