//! The hand-written [`crate::LaufeyBackendApi`] must have the exact layout of
//! `laufey_backend_api_t` in capi/include/laufey.h: a runtime reads this
//! struct through the header, so a field out of place calls the wrong
//! function. The reference is the capi crate's binding of the header
//! (bindgen), compared field by field.

use std::mem::{align_of, offset_of, size_of};

type Ours = crate::LaufeyBackendApi;
type Header = laufey::LaufeyBackendApi;

macro_rules! assert_same_layout {
  ($($field:ident),* $(,)?) => {
    // Every header field must be listed (and so present here): with each
    // listed field at the header's offset, equal sizes leave no room for a
    // field the header has and this struct lacks.
    assert_eq!(
      size_of::<Ours>(),
      size_of::<Header>(),
      "size of LaufeyBackendApi differs from laufey_backend_api_t"
    );
    assert_eq!(align_of::<Ours>(), align_of::<Header>());
    $(
      assert_eq!(
        offset_of!(Ours, $field),
        offset_of!(Header, $field),
        concat!("offset of ", stringify!($field)),
      );
    )*
  };
}

#[test]
fn vtable_layout_matches_the_header() {
  assert_same_layout!(
    version,
    backend_data,
    create_window,
    close_window,
    create_window_ex,
    navigate,
    set_title,
    execute_js,
    quit,
    set_window_size,
    get_window_size,
    set_window_position,
    get_window_position,
    set_resizable,
    is_resizable,
    set_always_on_top,
    is_always_on_top,
    is_visible,
    show,
    hide,
    focus,
    post_ui_task,
    value_is_null,
    value_is_bool,
    value_is_int,
    value_is_double,
    value_is_string,
    value_is_list,
    value_is_dict,
    value_is_binary,
    value_is_callback,
    value_get_bool,
    value_get_int,
    value_get_double,
    value_get_string,
    value_free_string,
    value_list_size,
    value_list_get,
    value_dict_get,
    value_dict_has,
    value_dict_size,
    value_dict_keys,
    value_free_keys,
    value_get_binary,
    value_get_callback_id,
    value_null,
    value_bool,
    value_int,
    value_double,
    value_string,
    value_list,
    value_dict,
    value_binary,
    value_list_append,
    value_list_set,
    value_dict_set,
    value_free,
    set_js_call_handler,
    js_call_respond,
    invoke_js_callback,
    release_js_callback,
    get_window_handle,
    get_display_handle,
    get_window_handle_type,
    set_keyboard_event_handler,
    set_mouse_click_handler,
    set_mouse_move_handler,
    set_wheel_handler,
    set_cursor_enter_leave_handler,
    set_focused_handler,
    set_resize_handler,
    set_move_handler,
    set_close_requested_handler,
    set_page_load_handler,
    poll_js_calls,
    set_js_call_notify,
    set_application_menu,
    show_context_menu,
    open_devtools,
    set_js_namespace,
    show_dialog,
    string_free,
    set_dock_badge,
    bounce_dock,
    set_dock_menu,
    set_dock_visible,
    set_dock_reopen_handler,
    create_tray_icon,
    destroy_tray_icon,
    set_tray_icon,
    set_tray_tooltip,
    set_tray_menu,
    set_tray_click_handler,
    set_tray_double_click_handler,
    set_tray_icon_dark,
    get_tray_icon_bounds,
    show_notification,
    close_notification,
    query_permission,
    request_permission,
    read_clipboard_text,
    write_clipboard_text,
    register_scheme_handler,
    scheme_request_read_body,
    scheme_response_begin,
    scheme_response_write,
    scheme_response_finish,
    set_window_opacity,
    get_window_opacity,
    test_click_menu_item,
    test_trigger_close_requested,
    print_to_pdf,
    set_click_passthrough,
    is_click_passthrough,
    set_click_passthrough_forward,
    is_click_passthrough_forward,
    set_open_url_handler,
    test_trigger_open_url,
    set_second_instance_handler,
    passkey_capabilities,
    passkey_request,
    get_window_scale_factor,
    get_window_inner_position,
    get_window_outer_size,
    test_inject_input,
    set_window_state,
    get_window_state,
    set_window_state_handler,
    set_window_size_constraints,
    get_window_size_constraints,
    get_screens,
    get_window_screen,
    set_display_changed_handler,
    window_capabilities,
    set_window_titlebar_style,
    set_window_traffic_light_position,
    set_window_backdrop,
    get_window_normal_bounds,
    set_quit_on_last_window_closed,
    set_file_drop_handler,
    start_file_drag,
    test_trigger_file_drop,
    show_file_dialog,
    cancel_file_dialog,
    test_file_dialog_respond,
    clipboard_capabilities,
    read_clipboard_html,
    write_clipboard_html,
    read_clipboard_image,
    write_clipboard_image,
    read_clipboard_formats,
    set_clipboard_change_handler,
    buffer_free,
    system_capabilities,
    set_shortcut_handler,
    register_shortcut,
    unregister_shortcut,
    unregister_all_shortcuts,
    list_shortcuts,
    canonicalize_accelerator,
    test_trigger_shortcut,
    get_launch_at_login,
    set_launch_at_login,
    close_devtools,
    is_devtools_open,
    is_devtools_enabled,
    menu_capabilities,
    show_context_menu_ex,
    test_dismiss_context_menu,
    test_trigger_menu_accelerator,
    notification_capabilities,
    set_notification_response_handler,
    list_scheduled_notifications,
    cancel_notification,
    test_notification_respond,
    dispatch_ui_task,
    is_ui_thread,
    auth_session_capabilities,
    auth_session_start,
    test_cancel_auth_session,
    auth_session_cancel
  );
}
