// Copyright 2025 Divy Srivastava. All rights reserved. MIT license.

#include "wv2_scheme_stream.h"

#include <shlwapi.h>
#include <wrl.h>

#include <algorithm>
#include <atomic>
#include <cctype>
#include <cstring>
#include <cwchar>
#include <iterator>
#include <map>
#include <memory>
#include <mutex>
#include <unordered_map>
#include <utility>

#include "runtime_loader.h"
#include "scheme_exchange.h"

using Microsoft::WRL::Callback;
using Microsoft::WRL::ComPtr;

namespace laufey_wv2 {

namespace {

// The shim's source (wv2_scheme_stream_shim.js), generated by CMake as one or
// more adjacent raw string literals.
const char kShimSource[] =
#include "wv2_scheme_stream_shim.inc"
    ;

// A tagged response still running this long after its head is streamed.
constexpr UINT kPushAfterMs = 50;
// A pushed response nobody attached to within this long is cancelled (the
// requesting document went away before its fetch resolved).
constexpr UINT kAttachTimeoutMs = 30000;
// Bytes posted to the page and not yet acknowledged by it.
constexpr size_t kCreditWindow = 4 * 1024 * 1024;
// Bytes held here while the page is not reading; past this the response
// fails instead of growing without bound (the runtime's write is never
// blocked: it runs on the runtime's event loop).
constexpr size_t kMaxQueued = 64 * 1024 * 1024;
// Payload bytes per posted message (base64 makes it 4/3 larger).
constexpr size_t kMessageBytes = 192 * 1024;

StreamHooks g_hooks;

std::wstring Utf8ToWide(const std::string& s) {
  if (s.empty())
    return std::wstring();
  int n = MultiByteToWideChar(CP_UTF8, 0, s.data(), static_cast<int>(s.size()),
                              nullptr, 0);
  std::wstring w(n, L'\0');
  MultiByteToWideChar(CP_UTF8, 0, s.data(), static_cast<int>(s.size()), &w[0],
                      n);
  return w;
}

std::string WideToUtf8(const wchar_t* s) {
  if (!s)
    return std::string();
  int n = WideCharToMultiByte(CP_UTF8, 0, s, -1, nullptr, 0, nullptr, nullptr);
  if (n <= 0)
    return std::string();
  std::string out(n - 1, '\0');
  WideCharToMultiByte(CP_UTF8, 0, s, -1, &out[0], n, nullptr, nullptr);
  return out;
}

std::string Lower(std::string s) {
  for (auto& c : s)
    c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
  return s;
}

// "<scheme>://<authority>" of a URL, scheme lowercased; empty if none.
std::string OriginOf(const std::string& url) {
  size_t sep = url.find("://");
  if (sep == std::string::npos || sep == 0)
    return std::string();
  size_t end = url.find_first_of("/?#", sep + 3);
  std::string authority = url.substr(
      sep + 3, end == std::string::npos ? std::string::npos : end - (sep + 3));
  return Lower(url.substr(0, sep)) + "://" + Lower(authority);
}

bool IsStreamId(const std::string& id) {
  if (id.size() != 32)
    return false;
  for (char c : id) {
    if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')))
      return false;
  }
  return true;
}

void AppendBase64(const uint8_t* p, size_t n, std::wstring* out) {
  static const char kAlphabet[] =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  out->reserve(out->size() + (n + 2) / 3 * 4);
  size_t i = 0;
  for (; i + 2 < n; i += 3) {
    uint32_t v = (p[i] << 16) | (p[i + 1] << 8) | p[i + 2];
    out->push_back(kAlphabet[(v >> 18) & 63]);
    out->push_back(kAlphabet[(v >> 12) & 63]);
    out->push_back(kAlphabet[(v >> 6) & 63]);
    out->push_back(kAlphabet[v & 63]);
  }
  if (i < n) {
    uint32_t v = p[i] << 16;
    if (i + 1 < n)
      v |= p[i + 1] << 8;
    out->push_back(kAlphabet[(v >> 18) & 63]);
    out->push_back(kAlphabet[(v >> 12) & 63]);
    out->push_back(i + 1 < n ? kAlphabet[(v >> 6) & 63] : L'=');
    out->push_back(L'=');
  }
}

// WebView2 takes the reason phrase separately and the runtime only sends the
// status; give the page the standard phrase (Response.statusText).
const wchar_t* ReasonPhrase(int status) {
  switch (status) {
    case 100:
      return L"Continue";
    case 101:
      return L"Switching Protocols";
    case 200:
      return L"OK";
    case 201:
      return L"Created";
    case 202:
      return L"Accepted";
    case 203:
      return L"Non-Authoritative Information";
    case 204:
      return L"No Content";
    case 205:
      return L"Reset Content";
    case 206:
      return L"Partial Content";
    case 300:
      return L"Multiple Choices";
    case 301:
      return L"Moved Permanently";
    case 302:
      return L"Found";
    case 303:
      return L"See Other";
    case 304:
      return L"Not Modified";
    case 307:
      return L"Temporary Redirect";
    case 308:
      return L"Permanent Redirect";
    case 400:
      return L"Bad Request";
    case 401:
      return L"Unauthorized";
    case 403:
      return L"Forbidden";
    case 404:
      return L"Not Found";
    case 405:
      return L"Method Not Allowed";
    case 406:
      return L"Not Acceptable";
    case 408:
      return L"Request Timeout";
    case 409:
      return L"Conflict";
    case 410:
      return L"Gone";
    case 412:
      return L"Precondition Failed";
    case 413:
      return L"Content Too Large";
    case 415:
      return L"Unsupported Media Type";
    case 416:
      return L"Range Not Satisfiable";
    case 421:
      return L"Misdirected Request";
    case 422:
      return L"Unprocessable Content";
    case 429:
      return L"Too Many Requests";
    case 500:
      return L"Internal Server Error";
    case 501:
      return L"Not Implemented";
    case 502:
      return L"Bad Gateway";
    case 503:
      return L"Service Unavailable";
    case 504:
      return L"Gateway Timeout";
    default:
      return L"";
  }
}

// One-shot UI-thread timers (SetTimer with no window; the UI thread's message
// loop dispatches WM_TIMER to the TIMERPROC). UI thread only.
std::map<UINT_PTR, std::function<void()>>& Timers() {
  static std::map<UINT_PTR, std::function<void()>> timers;
  return timers;
}

void CALLBACK OnTimer(HWND, UINT, UINT_PTR id, DWORD) {
  KillTimer(nullptr, id);
  auto& timers = Timers();
  auto it = timers.find(id);
  if (it == timers.end())
    return;
  std::function<void()> fn = std::move(it->second);
  timers.erase(it);
  fn();
}

void StartTimer(UINT ms, std::function<void()> fn) {
  UINT_PTR id = SetTimer(nullptr, 0, ms, &OnTimer);
  if (id)
    Timers()[id] = std::move(fn);
}

class Exchange;

// Every live exchange, by creation sequence, and the tagged ones by id. The
// registry owns a reference until the exchange completes or is cancelled.
std::mutex g_mutex;
std::map<uint64_t, std::shared_ptr<Exchange>> g_by_seq;
std::unordered_map<std::string, std::shared_ptr<Exchange>> g_by_id;
std::atomic<uint64_t> g_seq{0};
// Per window, the sequence number at the start of each pending main-frame
// navigation (UI thread only).
std::map<uint32_t, std::map<uint64_t, uint64_t>> g_nav_starts;

class Exchange : public std::enable_shared_from_this<Exchange> {
 public:
  Exchange(ComPtr<ICoreWebView2Environment> env,
           ComPtr<ICoreWebView2WebResourceRequestedEventArgs> args,
           ComPtr<ICoreWebView2Deferral> deferral, uint32_t window_id,
           std::string id, std::string origin, std::vector<uint8_t> body)
      : env_(std::move(env)),
        args_(std::move(args)),
        deferral_(std::move(deferral)),
        window_id_(window_id),
        id_(std::move(id)),
        origin_(std::move(origin)),
        seq_(++g_seq),
        request_body_(std::move(body)) {}

  uint32_t window_id() const {
    return window_id_;
  }
  const std::string& id() const {
    return id_;
  }
  uint64_t seq() const {
    return seq_;
  }

  // --- Runtime side (any thread; the runtime may also call these inline
  // from DispatchSchemeRequest on the UI thread).

  intptr_t ReadRequestBody(uint8_t* buf, size_t cap) {
    if (cap == 0)
      return 0;
    size_t remaining = request_body_.size() - req_cursor_;
    if (remaining == 0)
      return 0;
    size_t n = (std::min)(cap, remaining);
    memcpy(buf, request_body_.data() + req_cursor_, n);
    req_cursor_ += n;
    return static_cast<intptr_t>(n);
  }

  void Begin(int status, const char* headers, size_t headers_len) {
    {
      std::lock_guard<std::mutex> lock(mutex_);
      status_ = status;
      headers_ = LaufeyParseFlatHeaders(headers, headers_len);
      began_ = true;
    }
    if (!id_.empty()) {
      auto self = shared_from_this();
      g_hooks.run_on_ui(
          [self] { StartTimer(kPushAfterMs, [self] { self->StartPush(); }); });
    }
  }

  intptr_t WriteResponse(const uint8_t* buf, size_t len) {
    bool schedule = false;
    bool overflow = false;
    {
      std::lock_guard<std::mutex> lock(mutex_);
      if (cancelled_)
        return -1;
      body_.insert(body_.end(), buf, buf + len);
      if (mode_ == Mode::kPush) {
        if (body_.size() > kMaxQueued) {
          overflow = true;
          cancelled_ = true;
        } else if (attached_ && !flush_scheduled_) {
          flush_scheduled_ = true;
          schedule = true;
        }
      }
    }
    auto self = shared_from_this();
    if (overflow) {
      g_hooks.run_on_ui([self] {
        self->Fail("laufey: the page is not reading this response");
      });
      return -1;
    }
    if (schedule)
      g_hooks.run_on_ui([self] { self->Flush(); });
    return static_cast<intptr_t>(len);
  }

  void Finish() {
    Mode mode;
    {
      std::lock_guard<std::mutex> lock(mutex_);
      finished_ = true;
      mode = mode_;
    }
    auto self = shared_from_this();
    if (mode == Mode::kPush)
      g_hooks.run_on_ui([self] { self->Flush(); });
    else
      g_hooks.run_on_ui([self] { self->CompleteBuffered(); });
  }

  // --- UI thread.

  // The whole response is here: hand it to WebView2 in one piece.
  void CompleteBuffered() {
    std::vector<uint8_t> body;
    int status;
    std::vector<std::pair<std::string, std::string>> headers;
    {
      std::lock_guard<std::mutex> lock(mutex_);
      if (mode_ != Mode::kPending)
        return;
      mode_ = Mode::kBuffered;
      body.swap(body_);
      status = status_;
      headers = headers_;
    }
    Respond(status, headers, body.empty() ? nullptr : body.data(), body.size());
    Unregister();
  }

  // The response is still running kPushAfterMs after its head: send the head
  // now and push the body as it comes.
  void StartPush() {
    int status;
    std::vector<std::pair<std::string, std::string>> headers;
    {
      std::lock_guard<std::mutex> lock(mutex_);
      if (mode_ != Mode::kPending || finished_ || cancelled_ || !began_)
        return;
      mode_ = Mode::kPush;
      status = status_;
      for (const auto& [k, v] : headers_) {
        std::string name = Lower(k);
        // The body does not come through WebView2, so no length for it to
        // check; the shim reads the encoding itself.
        if (name == "content-length" || name == "x-laufey-stream")
          continue;
        headers.emplace_back(k, v);
      }
    }
    headers.emplace_back("x-laufey-stream", "push");
    Respond(status, headers, nullptr, 0);
    auto self = shared_from_this();
    StartTimer(kAttachTimeoutMs, [self] {
      bool attached;
      {
        std::lock_guard<std::mutex> lock(self->mutex_);
        attached = self->attached_;
      }
      if (!attached)
        self->Cancel();
    });
  }

  // The document that made the request asked for the body. `source_origin`
  // is the origin of the top-level document the message came from.
  void Attach(const std::string& source_origin) {
    {
      std::lock_guard<std::mutex> lock(mutex_);
      if (mode_ != Mode::kPush || attached_ || cancelled_)
        return;
      attached_ = source_origin == origin_;
    }
    // Only a document of the request's own origin may read it.
    if (attached_)
      Flush();
    else
      Cancel();
  }

  void Ack(size_t n) {
    {
      std::lock_guard<std::mutex> lock(mutex_);
      in_flight_ -= (std::min)(n, in_flight_);
    }
    Flush();
  }

  // Post what the credit window allows; the end once everything is out.
  void Flush() {
    std::vector<uint8_t> chunk;
    bool end = false;
    {
      std::lock_guard<std::mutex> lock(mutex_);
      flush_scheduled_ = false;
      if (mode_ != Mode::kPush || !attached_ || cancelled_ || end_sent_)
        return;
      size_t room = kCreditWindow - (std::min)(in_flight_, kCreditWindow);
      size_t n = (std::min)(room, body_.size());
      if (n > 0) {
        chunk.assign(body_.begin(), body_.begin() + n);
        body_.erase(body_.begin(), body_.begin() + n);
        in_flight_ += n;
      }
      if (finished_ && body_.empty()) {
        end_sent_ = true;
        end = true;
      }
    }
    bool ok = true;
    for (size_t off = 0; ok && off < chunk.size(); off += kMessageBytes) {
      size_t n = (std::min)(kMessageBytes, chunk.size() - off);
      std::wstring json = L"{\"__laufeyStream\":{\"t\":\"d\",\"id\":\"" +
                          Utf8ToWide(id_) + L"\",\"b\":\"";
      AppendBase64(chunk.data() + off, n, &json);
      json += L"\"}}";
      ok = g_hooks.post_json(window_id_, json);
    }
    if (!ok) {
      Cancel();
      return;
    }
    if (end) {
      g_hooks.post_json(window_id_,
                        L"{\"__laufeyStream\":{\"t\":\"e\",\"id\":\"" +
                            Utf8ToWide(id_) + L"\"}}");
      Unregister();
    }
  }

  // Stop: the runtime's next write fails, nothing more reaches the page.
  void Cancel() {
    {
      std::lock_guard<std::mutex> lock(mutex_);
      cancelled_ = true;
      body_.clear();
      body_.shrink_to_fit();
    }
    Unregister();
  }

  // Cancel, telling an attached page why. Also after the overflow check in
  // WriteResponse already marked the exchange cancelled.
  void Fail(const char* message) {
    bool attached;
    {
      std::lock_guard<std::mutex> lock(mutex_);
      attached = attached_ && !end_sent_;
      end_sent_ = true;
    }
    if (attached) {
      g_hooks.post_json(window_id_,
                        L"{\"__laufeyStream\":{\"t\":\"x\",\"id\":\"" +
                            Utf8ToWide(id_) + L"\",\"m\":\"" +
                            Utf8ToWide(message) + L"\"}}");
    }
    Cancel();
  }

 private:
  enum class Mode { kPending, kBuffered, kPush };

  void Respond(int status,
               const std::vector<std::pair<std::string, std::string>>& headers,
               const uint8_t* body, size_t len) {
    ComPtr<IStream> stream;
    stream.Attach(SHCreateMemStream(body, static_cast<UINT>(len)));
    std::wstring headers_w;
    for (const auto& [k, v] : headers)
      headers_w += Utf8ToWide(k) + L": " + Utf8ToWide(v) + L"\r\n";
    ComPtr<ICoreWebView2WebResourceResponse> response;
    if (env_) {
      env_->CreateWebResourceResponse(stream.Get(), status,
                                      ReasonPhrase(status), headers_w.c_str(),
                                      &response);
      if (response)
        args_->put_Response(response.Get());
    }
    deferral_->Complete();
    // WebView2 holds what it needs; drop the event objects now rather than
    // with the (possibly long-lived) exchange.
    deferral_.Reset();
    args_.Reset();
    env_.Reset();
  }

  void Unregister() {
    std::lock_guard<std::mutex> lock(g_mutex);
    g_by_seq.erase(seq_);
    if (!id_.empty()) {
      auto it = g_by_id.find(id_);
      if (it != g_by_id.end() && it->second.get() == this)
        g_by_id.erase(it);
    }
  }

  ComPtr<ICoreWebView2Environment> env_;
  ComPtr<ICoreWebView2WebResourceRequestedEventArgs> args_;
  ComPtr<ICoreWebView2Deferral> deferral_;
  const uint32_t window_id_;
  const std::string id_;      // empty: not from the shim, always buffered
  const std::string origin_;  // of the request URL
  const uint64_t seq_;
  std::vector<uint8_t> request_body_;
  size_t req_cursor_ = 0;

  std::mutex mutex_;
  Mode mode_ = Mode::kPending;
  int status_ = 200;
  std::vector<std::pair<std::string, std::string>> headers_;
  bool began_ = false;
  // Not yet handed to WebView2 (buffered) or posted to the page (push).
  std::vector<uint8_t> body_;
  size_t in_flight_ = 0;
  bool finished_ = false;
  bool cancelled_ = false;
  bool attached_ = false;
  bool flush_scheduled_ = false;
  bool end_sent_ = false;
};

// What the runtime holds: released by Finish(); the exchange itself lives on
// while it is registered or has UI work queued.
class ExchangeHandle : public SchemeExchangeBase {
 public:
  explicit ExchangeHandle(std::shared_ptr<Exchange> x) : x_(std::move(x)) {}
  intptr_t ReadRequestBody(uint8_t* buf, size_t cap) override {
    return x_->ReadRequestBody(buf, cap);
  }
  void Begin(int status, const char* headers, size_t headers_len) override {
    x_->Begin(status, headers, headers_len);
  }
  intptr_t WriteResponse(const uint8_t* buf, size_t len) override {
    return x_->WriteResponse(buf, len);
  }
  void Finish() override {
    x_->Finish();
    delete this;
  }

 private:
  std::shared_ptr<Exchange> x_;
};

std::shared_ptr<Exchange> FindById(const std::string& id) {
  std::lock_guard<std::mutex> lock(g_mutex);
  auto it = g_by_id.find(id);
  return it == g_by_id.end() ? nullptr : it->second;
}

void CancelWhere(const std::function<bool(const Exchange&)>& pred) {
  std::vector<std::shared_ptr<Exchange>> victims;
  {
    std::lock_guard<std::mutex> lock(g_mutex);
    for (const auto& [seq, x] : g_by_seq) {
      if (pred(*x))
        victims.push_back(x);
    }
  }
  for (auto& x : victims)
    x->Cancel();
}

// Extracts `"<key>":"<value>"` (value without escapes) or `"<key>":<digits>`.
bool JsonField(const std::string& s, const char* key, std::string* out) {
  std::string needle = std::string("\"") + key + "\":";
  size_t p = s.find(needle);
  if (p == std::string::npos)
    return false;
  p += needle.size();
  if (p < s.size() && s[p] == '"') {
    size_t end = s.find('"', p + 1);
    if (end == std::string::npos)
      return false;
    *out = s.substr(p + 1, end - p - 1);
    return true;
  }
  size_t end = p;
  while (end < s.size() && s[end] >= '0' && s[end] <= '9')
    end++;
  if (end == p)
    return false;
  *out = s.substr(p, end - p);
  return true;
}

}  // namespace

void InitSchemeStreams(StreamHooks hooks) {
  g_hooks = std::move(hooks);
}

std::string BuildSchemeStreamShimScript(
    const std::vector<std::string>& schemes) {
  std::string list = "[";
  for (size_t i = 0; i < schemes.size(); i++) {
    // Scheme names are validated ([a-z][a-z0-9+.-]*); no quoting needed.
    if (i)
      list += ",";
    list += "\"" + Lower(schemes[i]) + "\"";
  }
  list += "]";
  return "{ const __laufeySchemes = " + list + ";\n" + kShimSource + "\n}\n";
}

HRESULT HandleSchemeRequest(ICoreWebView2Environment* env,
                            ICoreWebView2WebResourceRequestedEventArgs* args,
                            uint32_t window_id) {
  // This runs inside a WebView2 COM event callback. A C++ exception unwinding
  // back through WebView2's (non-EH) frames would reach std::terminate and
  // crash the whole process — on Windows that surfaces as exit code
  // 0xc0000409 (STATUS_STACK_BUFFER_OVERRUN). Contain everything here.
  try {
    ComPtr<ICoreWebView2WebResourceRequest> request;
    if (FAILED(args->get_Request(&request)) || !request)
      return S_OK;

    LPWSTR uri_raw = nullptr;
    request->get_Uri(&uri_raw);
    LPWSTR method_raw = nullptr;
    request->get_Method(&method_raw);
    std::string url = WideToUtf8(uri_raw);
    std::string method = method_raw ? WideToUtf8(method_raw) : "GET";
    if (uri_raw)
      CoTaskMemFree(uri_raw);
    if (method_raw)
      CoTaskMemFree(method_raw);

    std::string stream_id;
    std::vector<std::pair<std::string, std::string>> headers;
    ComPtr<ICoreWebView2HttpRequestHeaders> req_headers;
    if (SUCCEEDED(request->get_Headers(&req_headers)) && req_headers) {
      ComPtr<ICoreWebView2HttpHeadersCollectionIterator> it;
      if (SUCCEEDED(req_headers->GetIterator(&it)) && it) {
        BOOL has_current = FALSE;
        while (SUCCEEDED(it->get_HasCurrentHeader(&has_current)) &&
               has_current) {
          LPWSTR name = nullptr;
          LPWSTR value = nullptr;
          if (SUCCEEDED(it->GetCurrentHeader(&name, &value))) {
            std::string n = WideToUtf8(name);
            std::string v = WideToUtf8(value);
            // The shim's tag is transport, not part of the request.
            if (Lower(n) == "x-laufey-stream")
              stream_id = v;
            else
              headers.emplace_back(std::move(n), std::move(v));
            if (name)
              CoTaskMemFree(name);
            if (value)
              CoTaskMemFree(value);
          }
          BOOL has_next = FALSE;
          if (FAILED(it->MoveNext(&has_next)) || !has_next)
            break;
        }
      }
    }

    std::vector<uint8_t> body;
    ComPtr<IStream> content;
    if (SUCCEEDED(request->get_Content(&content)) && content) {
      uint8_t chunk[16 * 1024];
      ULONG read = 0;
      while (SUCCEEDED(content->Read(chunk, sizeof(chunk), &read)) &&
             read > 0) {
        body.insert(body.end(), chunk, chunk + read);
      }
    }

    ComPtr<ICoreWebView2Deferral> deferral;
    args->GetDeferral(&deferral);

    if (!IsStreamId(stream_id) || FindById(stream_id))
      stream_id.clear();
    auto exchange =
        std::make_shared<Exchange>(env, args, deferral, window_id, stream_id,
                                   OriginOf(url), std::move(body));
    {
      std::lock_guard<std::mutex> lock(g_mutex);
      g_by_seq[exchange->seq()] = exchange;
      if (!stream_id.empty())
        g_by_id[stream_id] = exchange;
    }

    std::string flat = LaufeyFlattenHeaders(headers);
    // window_id is unused by the desktop bridge (single named channel).
    RuntimeLoader::GetInstance()->DispatchSchemeRequest(
        0, new ExchangeHandle(exchange), method, url, flat);
    return S_OK;
  } catch (...) {
    return S_OK;
  }
}

bool HandleStreamMessage(uint32_t window_id, const wchar_t* message,
                         const wchar_t* source) {
  static const wchar_t kPrefix[] = L"{\"__laufeyStream\":{";
  if (!message || wcsncmp(message, kPrefix, wcslen(kPrefix)) != 0)
    return false;
  std::string m = WideToUtf8(message);
  std::string t, id, n;
  if (!JsonField(m, "t", &t) || !JsonField(m, "id", &id) || !IsStreamId(id))
    return true;
  auto x = FindById(id);
  if (!x || x->window_id() != window_id)
    return true;
  if (t == "attach") {
    x->Attach(OriginOf(WideToUtf8(source)));
  } else if (t == "ack") {
    if (JsonField(m, "n", &n) && n.size() < 12)
      x->Ack(static_cast<size_t>(std::stoull(n)));
  } else if (t == "cancel") {
    x->Cancel();
  }
  return true;
}

void OnNavigationStarting(uint32_t window_id, uint64_t navigation_id) {
  g_nav_starts[window_id][navigation_id] = g_seq.load();
}

void OnNavigationCommitted(uint32_t window_id, uint64_t navigation_id) {
  auto w = g_nav_starts.find(window_id);
  if (w == g_nav_starts.end())
    return;
  auto it = w->second.find(navigation_id);
  if (it == w->second.end())
    return;
  uint64_t before = it->second;
  // Navigations started earlier than this one can no longer commit.
  w->second.erase(w->second.begin(), std::next(it));
  // Responses requested by the document this navigation replaced.
  CancelWhere([&](const Exchange& x) {
    return x.window_id() == window_id && x.seq() <= before;
  });
}

void CancelStreamsForWindow(uint32_t window_id) {
  g_nav_starts.erase(window_id);
  CancelWhere([&](const Exchange& x) { return x.window_id() == window_id; });
}

}  // namespace laufey_wv2
